transition-zero/tz-osemosys

- tz/osemosys/__init__.py
> fix: make load_model importable from top level

- tz/osemosys/model/constraints/__init__.py
- tz/osemosys/model/constraints/accounting_technology.py
- tz/osemosys/model/constraints/annual_activity.py
- tz/osemosys/model/constraints/capacity_adequacy_a.py
- tz/osemosys/model/constraints/capacity_adequacy_b.py
- tz/osemosys/model/constraints/capital_costs.py
- tz/osemosys/model/constraints/demand.py
- tz/osemosys/model/constraints/emissions.py
- tz/osemosys/model/constraints/energy_balance_a.py
- tz/osemosys/model/constraints/energy_balance_b.py
- tz/osemosys/model/constraints/new_capacity.py
- tz/osemosys/model/constraints/operating_costs.py
- tz/osemosys/model/constraints/re_targets.py
- tz/osemosys/model/constraints/reserve_margin.py
- tz/osemosys/model/constraints/salvage_value.py
- tz/osemosys/model/constraints/storage.py
- tz/osemosys/model/constraints/total_activity.py
- tz/osemosys/model/constraints/total_capacity.py
- tz/osemosys/model/constraints/total_discounted_costs.py
- tz/osemosys/model/linear_expressions/__init__.py
- tz/osemosys/model/linear_expressions/activity.py
- tz/osemosys/model/linear_expressions/capacity.py
- tz/osemosys/model/linear_expressions/emissions.py
- tz/osemosys/model/linear_expressions/financials.py
- tz/osemosys/model/linear_expressions/production.py
- tz/osemosys/model/linear_expressions/reserve_margin.py
- tz/osemosys/model/model.py
> [ENG-864] linear expressions

- docs/time_definition.md
- examples/CAISO-ERCOT-IC/main.yaml
- tests/test_construction/test_timedefinition.py
- tests/test_solve/test_solve.py
- tz/osemosys/schemas/time_definition.py
- tz/osemosys/schemas/validation/timedefinition_validation.py
Fixed bug in time definition when constructing seasons and dailytimebrackets from integers.
> [ENG-822] fix timedef bug

- examples/quickstart/main.yaml
> feat: quickstart model yaml

- tests/test_construction/test_load_from_yaml.py
- tz/osemosys/io/load_model.py
- tz/osemosys/utils/cfg_parser.py
yaml parse was failing when nested comprehensions.
> [ENG-1076] walk cfg until all nested comprehensions are evalled

- tz/osemosys/model/linear_expressions/production.py
Added `ProductionByTechnology` to solution via Linear Expressions.
> [ENG-1086] feat: Added ProductionByTechnology to solution

- tz/osemosys/schemas/validation/region_validation.py
- tz/osemosys/schemas/validation/validation_utils.py
- tz/osemosys/utils/utils.py
> [ENG-1120]: Switch to json_normalise

- tz/osemosys/utils/utils.py
Small changes to `utils.json_dict_to_dataframe` to unblock `Runspec` work in `tz-mod`
> NO-TICKET-Fix-Unblock-Runspec-Work

- tests/test_construction/test_timedefinition.py
- tz/osemosys/schemas/time_definition.py
- tz/osemosys/schemas/validation/timedefinition_validation.py
> [ENG-1139] TimeDefinition roundtrip

- tz/osemosys/model/constraints/capacity_adequacy_a.py
- tz/osemosys/model/constraints/capacity_adequacy_b.py
- tz/osemosys/model/constraints/total_capacity.py
- tz/osemosys/model/linear_expressions/capacity.py
- tz/osemosys/model/linear_expressions/financials.py
- tz/osemosys/model/linear_expressions/reserve_margin.py
- tz/osemosys/model/model.py
- tz/osemosys/model/solution.py
- made solution variables sorted and controllable by the user, with a default list provided
- added a set of default solution keys
- renamed `TotalCapacityAnnual` -> `GrossCapacity`
> [NO-TICKET] cleanup solution

- tests/test_construction/test_technology.py
- tz/osemosys/schemas/base.py
- tz/osemosys/schemas/technology.py
> Eng-1137/feature-enable-roundtrip-technologies

- tz/osemosys/model/solution.py
- add the emissions linear expression to the solution obj
> [ENG-1170] add maybe emissions to solution

- tz/osemosys/model/constraints/trade.py
Update trade constraints for Import and Export to include `ds['TradeRoute']`. Previously, these constraints allowed imports without requiring associated capacity to be built on a given trade route.
> Updated trade capacity constraints to include TradeRoute

- tz/osemosys/schemas/base.py
> Add check if ":" included in id

- docs/technology.md
- tests/test_solve/test_growth_rates.py
- tz/osemosys/model/constraints/capacity_growth_rate.py
- tz/osemosys/model/variables/capacity.py
- tz/osemosys/schemas/compat/technology.py
- tz/osemosys/schemas/technology.py
> [Eng-1446] fix growth rate constraint

- README.md
- pyproject.toml
- tz/osemosys/__init__.py
- tz/osemosys/io/load_model.py
> Use cloudpathlib if installed to load yaml directly from cloud object storage

- README.md
- docs/index.md
- docs/model.md
- tests/test_solve/test_solve.py
- tz/osemosys/model/model.py
- tz/osemosys/schemas/model.py
> [ENG-1518] update solution handling and documentation

- .github/workflows/tz-solve-osemosys-build-webhook.yml
Remove unwanted verbosity from curl command in trigger webhook workflow + extra tidy up.
Also testing workflow will trigger on PR merge.
> chore: tidy up tz-solve-osemosys-build-webhook workflow

- docs/trade.md
- tz/osemosys/defaults.py
- tz/osemosys/model/constraints/energy_balance_a.py
- tz/osemosys/model/constraints/energy_balance_b.py
- tz/osemosys/model/constraints/trade.py
- tz/osemosys/model/linear_expressions/__init__.py
- tz/osemosys/model/linear_expressions/financials.py
- tz/osemosys/schemas/compat/trade.py
- tz/osemosys/schemas/trade.py
> [ENG-1633] Add capacity_activity_unit_ratio to trade

- docs/trade.md
- tz/osemosys/defaults.py
- tz/osemosys/model/constraints/energy_balance_a.py
- tz/osemosys/model/constraints/energy_balance_b.py
- tz/osemosys/model/constraints/trade.py
- tz/osemosys/model/linear_expressions/__init__.py
- tz/osemosys/model/linear_expressions/financials.py
- tz/osemosys/schemas/compat/trade.py
- tz/osemosys/schemas/trade.py
Reverts transition-zero/tz-osemosys#143
> Revert "[ENG-1633] Add capacity_activity_unit_ratio to trade"

- tz/osemosys/model/model.py
Prevent attribute errors if model solution is infeasible and solution therefore doesn't exist.
> Fix non optimal termination objective value

- examples/two-region-model/README.md
Fixed a minor issue in pathing of tutorial
> fix pathing

- docs/ALL_DOCUMENTATION.md
> add combined documentation file

- .github/workflows/pypi_publish.yml
- .github/workflows/test_pypi_publish.yml
> chore: bump actions/upload-artefact to v4

- .github/workflows/pypi_publish.yml
- .github/workflows/test_pypi_publish.yml
> chore: bump actions/download-artefact to v4

- .github/workflows/pypi_publish.yml
> chore: bump sigstore/gh-action-sigstore-python to v3

- .github/workflows/pypi_publish.yml
> Bump gh action sigstore python v3

- README.md
> remove dead links in readme

- pyproject.toml
> chore: unpin xarray
